# syntax=docker/dockerfile:1.9
#
# TaskIQ scheduler image. Build doci-base first, then this image:
#   docker build -f docker/Dockerfile.base      -t doci-base      .
#   docker build -f docker/Dockerfile.scheduler -t doci-scheduler .
ARG BASE_IMAGE=doci-base:latest
FROM ${BASE_IMAGE}
ENTRYPOINT ["doci-scheduler"]