# syntax=docker/dockerfile:1.9
#
# API + in-process worker image. Build doci-base first, then this image:
#   docker build -f docker/Dockerfile.base       -t doci-base       .
#   docker build -f docker/Dockerfile.all_in_one -t doci-all-in-one .
ARG BASE_IMAGE=doci-base:latest
FROM ${BASE_IMAGE}
ENV HOST=0.0.0.0 \
    PORT=8000
EXPOSE 8000
ENTRYPOINT ["doci-all-in-one"]
